import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { CartProvider } from '../contexts/CartContext'; // Adjust the path if necessary
import CartSummary from "../components/CartSummary"; // Make sure CartSummary is correctly imported
import "react-datepicker/dist/react-datepicker.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Wrap the entire app with CartProvider */}
        <CartProvider>
          <nav className="bg-[#fe0600] p-1">
            <div className="container mx-auto flex justify-between items-center">
              <Link href="/">
                <Image src="/images/logo.jpg" alt="Logo" width={120} height={50} />
              </Link>
              <ul className="flex space-x-6">
                {[
                  { href: "/register", label: "REGISTER" },
                  { href: "/book-a-session", label: "BOOK A SESSION" },
                  { href: "/coaching", label: "COACHING" },
                  { href: "/times-prices", label: "TIMES & PRICES" },
                  { href: "/first-time", label: "FIRST TIME" },
                  { href: "/parties", label: "PARTIES" },
                  { href: "/faq", label: "FAQ" },
                  { href: "/charity", label: "CHARITY" },
                  { href: "/events", label: "EVENTS" },
                  { href: "/find-us", label: "FIND US" },
                ].map((item) => (
                  <li key={item.href}>
                    <Link
                      href={item.href}
                      className="text-white font-bold hover:underline"
                    >
                      {item.label}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
          </nav>
          <main className="w-screen overflow-x-hidden">{children}</main>
          {/* CartSummary will be visible on all pages */}
          <CartSummary />
        </CartProvider>
      </body>
    </html>
  );
}
